version: 2.0

jobs:
    build:
        docker:
            - image: circleci/openjdk:8-jdk
        steps:
            - checkout
            - name: Build
              run: ./gradlew compileKotlin
            - name: Test
              run: ./gradlew test
            - name: Check
              run: ./gradlew check
      
