version: 2.0

jobs:
    build:
        docker:
            - image: circleci/openjdk:8-jdk
        steps:
            - checkout
            - run: ./gradlew compileKotlin
            - run: ./gradlew test
            - run: ./gradlew check
      
