name: CIBuild

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: 11
        cache: gradle
        distribution: zulu
    - name: Checking kotlin formatting
      run: ./gradlew ktlintCheck
    - name: Compiling and test
      run: ./gradlew check